/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderDrawer: typeof import('./src/components/header/HeaderDrawer.vue')['default']
    HeaderMenu: typeof import('./src/components/header/HeaderMenu.vue')['default']
    ProducerTemplateConverter: typeof import('./src/components/ProducerTemplateConverter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMusicCard: typeof import('./src/components/SearchMusicCard.vue')['default']
    SongDialog: typeof import('./src/components/SongDialog.vue')['default']
  }
}
